#!/usr/bin/env python3
"""Generate po files with correct UTF-8 (no merge from broken sources)."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PO_DIR = ROOT / "po"

HEADER = '''msgid ""
msgstr ""
"Project-Id-Version: linux-custom-resolution 1.0.0\\n"
"Language: {lang}\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\\n"
'''

MSGIDS = [
    "Linux Custom Resolution",
    "Refresh monitors",
    "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.",
    "xrandr is not available. Install xorg-xrandr on your system.",
    "New Resolution",
    "Monitor",
    "Width",
    "Height",
    "Refresh Rate (Hz)",
    "Add to System",
    "Add and Apply",
    "Restore default",
    "Monitor {output} restored to default resolution.",
    "Saved Resolutions",
    "No saved resolutions yet.",
    "No connected monitor found.",
    "No monitor",
    "Select a valid monitor.",
    "Resolution {details} added and applied.",
    "Resolution {details} added to the system.",
    "Resolution {details} applied.",
    "Resolution not found.",
    "Removed from profile, but xrandr failed: {error}",
    "Removed {details}.",
    "Applied on startup",
    "Manual use",
    "Language",
    "System Default",
    "English",
    "Portuguese (Brazil)",
    "Spanish",
    "Russian",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "French",
    "German",
    "Japanese",
    "Arabic",
    "Hindi",
    "Italian",
    "Korean",
    "Edit resolution",
    "Apply this resolution now",
    "Remove saved resolution",
    "Remove saved resolution?",
    "Remove {details} from your saved resolutions?",
    "Remove",
    "On startup",
    "Edit Resolution",
    "Apply when the computer starts",
    "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.",
    "Save Changes",
    "Save and Apply",
    "Cancel",
    "Failed to update resolution: {error}",
    "Resolution {details} updated and applied.",
    "Resolution {details} updated.",
    "Resolution already saved",
    "{details} is already saved for monitor {output}.",
    "Apply saved",
    "Another saved resolution already uses these settings.",
    "OK",
    "xrandr is not available.",
    "Supported resolutions",
    "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.",
    "No modes reported for this display.",
    "{resolution} — {rates} Hz",
    " (active: {rate:g} Hz)",
    "{rates} Hz",
    " · active: {rate:g} Hz",
    "Use",
    "Close",
    "Apply now",
    "Fill form fields",
    "Current",
    "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.",
    "({count} supported modes)",
    "Fields filled with {details}.",
    "Saved resolutions for {output}",
    "No saved resolutions for this monitor.",
    "Added and applied.",
    "Added to the system.",
    "Applied.",
    "Updated and applied.",
    "Updated.",
    "Removed.",
    "Fields filled.",
]

TRANSLATIONS: dict[str, dict[str, str]] = {
    "pt_BR": {
        "Refresh monitors": "Atualizar monitores",
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "Sessão Wayland detectada. O LCR utiliza xrandr (X11) e funciona melhor em sessões X11 ou quando o compositor oferece XWayland.",
        "xrandr is not available. Install xorg-xrandr on your system.": "O xrandr não está disponível. Instale o pacote xorg-xrandr no sistema.",
        "New Resolution": "Nova resolução",
        "Monitor": "Monitor",
        "Width": "Largura",
        "Height": "Altura",
        "Refresh Rate (Hz)": "Taxa de atualização (Hz)",
        "Add to System": "Adicionar ao sistema",
        "Add and Apply": "Adicionar e aplicar",
        "Restore default": "Restaurar padrão",
        "Monitor {output} restored to default resolution.": "Monitor {output} restaurado ao padrão.",
        "Saved Resolutions": "Resoluções salvas",
        "No saved resolutions yet.": "Nenhuma resolução salva.",
        "No connected monitor found.": "Nenhum monitor conectado encontrado.",
        "No monitor": "Nenhum monitor",
        "Select a valid monitor.": "Selecione um monitor válido.",
        "Resolution {details} added and applied.": "Resolução {details} adicionada e aplicada.",
        "Resolution {details} added to the system.": "Resolução {details} adicionada ao sistema.",
        "Resolution {details} applied.": "Resolução {details} aplicada.",
        "Resolution not found.": "Resolução não encontrada.",
        "Removed from profile, but xrandr failed: {error}": "Removida do perfil, mas o xrandr falhou: {error}",
        "Removed {details}.": "Resolução {details} removida.",
        "Applied on startup": "Aplicada ao iniciar",
        "Manual use": "Uso manual",
        "Language": "Idioma",
        "System Default": "Padrão do sistema",
        "English": "Inglês",
        "Portuguese (Brazil)": "Português (Brasil)",
        "Spanish": "Espanhol",
        "Russian": "Russo",
        "Chinese (Simplified)": "Chinês (simplificado)",
        "Chinese (Traditional)": "Chinês (tradicional)",
        "French": "Francês",
        "German": "Alemão",
        "Japanese": "Japonês",
        "Arabic": "Árabe",
        "Hindi": "Hindi",
        "Italian": "Italiano",
        "Korean": "Coreano",
        "Edit resolution": "Editar resolução",
        "Apply this resolution now": "Aplicar esta resolução agora",
        "Remove saved resolution": "Remover resolução salva",
        "Remove saved resolution?": "Remover resolução salva?",
        "Remove {details} from your saved resolutions?": "Remover {details} da lista de resoluções salvas?",
        "Remove": "Remover",
        "On startup": "Ao iniciar",
        "Edit Resolution": "Editar resolução",
        "Apply when the computer starts": "Aplicar ao iniciar o computador",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "Se ativado, esta resolução é selecionada automaticamente após login ou reinício. Se desativado, ela permanece salva e você escolhe quando usá-la.",
        "Save Changes": "Salvar alterações",
        "Save and Apply": "Salvar e aplicar",
        "Cancel": "Cancelar",
        "Failed to update resolution: {error}": "Falha ao atualizar a resolução: {error}",
        "Resolution {details} updated and applied.": "Resolução {details} atualizada e aplicada.",
        "Resolution {details} updated.": "Resolução {details} atualizada.",
        "Resolution already saved": "Resolução já salva",
        "{details} is already saved for monitor {output}.": "{details} já está salva para o monitor {output}.",
        "Apply saved": "Aplicar resolução salva",
        "Another saved resolution already uses these settings.": "Outra resolução salva já usa essas configurações.",
        "OK": "OK",
        "xrandr is not available.": "O xrandr não está disponível.",
    },
    "fr": {
        "Refresh monitors": "Actualiser les moniteurs",
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "Session Wayland détectée. LCR utilise xrandr (X11) et fonctionne mieux en session X11 ou lorsque le compositeur expose XWayland.",
        "xrandr is not available. Install xorg-xrandr on your system.": "xrandr n'est pas disponible. Installez xorg-xrandr sur votre système.",
        "New Resolution": "Nouvelle résolution",
        "Monitor": "Moniteur",
        "Width": "Largeur",
        "Height": "Hauteur",
        "Refresh Rate (Hz)": "Fréquence (Hz)",
        "Add to System": "Ajouter au système",
        "Add and Apply": "Ajouter et appliquer",
        "Restore default": "Rétablir par défaut",
        "Monitor {output} restored to default resolution.": "Moniteur {output} rétabli à la résolution par défaut.",
        "Saved Resolutions": "Résolutions enregistrées",
        "No saved resolutions yet.": "Aucune résolution enregistrée.",
        "No connected monitor found.": "Aucun moniteur connecté trouvé.",
        "No monitor": "Aucun moniteur",
        "Select a valid monitor.": "Sélectionnez un moniteur valide.",
        "Resolution {details} added and applied.": "Résolution {details} ajoutée et appliquée.",
        "Resolution {details} added to the system.": "Résolution {details} ajoutée au système.",
        "Resolution {details} applied.": "Résolution {details} appliquée.",
        "Resolution not found.": "Résolution introuvable.",
        "Removed from profile, but xrandr failed: {error}": "Supprimée du profil, mais xrandr a échoué : {error}",
        "Removed {details}.": "Résolution {details} supprimée.",
        "Applied on startup": "Appliquée au démarrage",
        "Manual use": "Utilisation manuelle",
        "Language": "Langue",
        "System Default": "Par défaut du système",
        "English": "Anglais",
        "Portuguese (Brazil)": "Portugais (Brésil)",
        "Spanish": "Espagnol",
        "Russian": "Russe",
        "Chinese (Simplified)": "Chinois (simplifié)",
        "Chinese (Traditional)": "Chinois (traditionnel)",
        "French": "Français",
        "German": "Allemand",
        "Japanese": "Japonais",
        "Arabic": "Arabe",
        "Hindi": "Hindi",
        "Italian": "Italien",
        "Korean": "Coréen",
        "Edit resolution": "Modifier la résolution",
        "Apply this resolution now": "Appliquer cette résolution maintenant",
        "Remove saved resolution": "Supprimer la résolution enregistrée",
        "Remove saved resolution?": "Supprimer la résolution enregistrée ?",
        "Remove {details} from your saved resolutions?": "Supprimer {details} de vos résolutions enregistrées ?",
        "Remove": "Supprimer",
        "On startup": "Au démarrage",
        "Edit Resolution": "Modifier la résolution",
        "Apply when the computer starts": "Appliquer au démarrage de l'ordinateur",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "Si activé, cette résolution est sélectionnée automatiquement après connexion ou redémarrage. Si désactivé, elle reste enregistrée et vous choisissez quand l'utiliser.",
        "Save Changes": "Enregistrer les modifications",
        "Save and Apply": "Enregistrer et appliquer",
        "Cancel": "Annuler",
        "Failed to update resolution: {error}": "Échec de la mise à jour de la résolution : {error}",
        "Resolution {details} updated and applied.": "Résolution {details} mise à jour et appliquée.",
        "Resolution {details} updated.": "Résolution {details} mise à jour.",
        "Resolution already saved": "Résolution déjà enregistrée",
        "{details} is already saved for monitor {output}.": "{details} est déjà enregistrée pour le moniteur {output}.",
        "Apply saved": "Appliquer la résolution enregistrée",
        "Another saved resolution already uses these settings.": "Une autre résolution enregistrée utilise déjà ces paramètres.",
        "OK": "OK",
        "xrandr is not available.": "xrandr n'est pas disponible.",
    },
    "es": {
        "Refresh monitors": "Actualizar monitores",
        "New Resolution": "Nueva resolución",
        "Monitor": "Monitor",
        "Width": "Ancho",
        "Height": "Alto",
        "Refresh Rate (Hz)": "Frecuencia (Hz)",
        "Add to System": "Añadir al sistema",
        "Add and Apply": "Añadir y aplicar",
        "Restore default": "Restaurar predeterminado",
        "Monitor {output} restored to default resolution.": "Monitor {output} restaurado a la resolución predeterminada.",
        "Saved Resolutions": "Resoluciones guardadas",
        "No saved resolutions yet.": "No hay resoluciones guardadas.",
        "No connected monitor found.": "No se encontró ningún monitor conectado.",
        "No monitor": "Ningún monitor",
        "Select a valid monitor.": "Seleccione un monitor válido.",
        "Applied on startup": "Aplicada al iniciar",
        "Manual use": "Uso manual",
        "Language": "Idioma",
        "System Default": "Predeterminado del sistema",
        "English": "Inglés",
        "Portuguese (Brazil)": "Portugués (Brasil)",
        "Spanish": "Español",
        "Russian": "Ruso",
        "Chinese (Simplified)": "Chino (simplificado)",
        "Chinese (Traditional)": "Chino (tradicional)",
        "French": "Francés",
        "German": "Alemán",
        "Japanese": "Japonés",
        "Arabic": "Árabe",
        "Hindi": "Hindi",
        "Italian": "Italiano",
        "Korean": "Coreano",
        "Edit resolution": "Editar resolución",
        "Apply this resolution now": "Aplicar esta resolución ahora",
        "Remove saved resolution": "Eliminar resolución guardada",
        "Remove saved resolution?": "¿Eliminar resolución guardada?",
        "Remove {details} from your saved resolutions?": "¿Eliminar {details} de las resoluciones guardadas?",
        "Remove": "Eliminar",
        "On startup": "Al iniciar",
        "Edit Resolution": "Editar resolución",
        "Apply when the computer starts": "Aplicar al iniciar el equipo",
        "Save Changes": "Guardar cambios",
        "Save and Apply": "Guardar y aplicar",
        "Cancel": "Cancelar",
        "Resolution already saved": "Resolución ya guardada",
        "{details} is already saved for monitor {output}.": "{details} ya está guardada para el monitor {output}.",
        "Apply saved": "Aplicar resolución guardada",
        "Another saved resolution already uses these settings.": "Otra resolución guardada ya usa esta configuración.",
        "OK": "Aceptar",
        "xrandr is not available.": "xrandr no está disponible.",
    },
    "ru": {
        "Refresh monitors": "Обновить мониторы",
        "New Resolution": "Новое разрешение",
        "Monitor": "Монитор",
        "Width": "Ширина",
        "Height": "Высота",
        "Refresh Rate (Hz)": "Частота (Гц)",
        "Add to System": "Добавить в систему",
        "Add and Apply": "Добавить и применить",
        "Restore default": "Восстановить стандарт",
        "Monitor {output} restored to default resolution.": "Монитор {output} восстановлен до стандартного разрешения.",
        "Saved Resolutions": "Сохранённые разрешения",
        "No saved resolutions yet.": "Нет сохранённых разрешений.",
        "No connected monitor found.": "Подключённые мониторы не найдены.",
        "No monitor": "Нет монитора",
        "Select a valid monitor.": "Выберите действительный монитор.",
        "Applied on startup": "Применяется при запуске",
        "Manual use": "Ручное использование",
        "Language": "Язык",
        "System Default": "По умолчанию в системе",
        "English": "Английский",
        "Portuguese (Brazil)": "Португальский (Бразилия)",
        "Spanish": "Испанский",
        "Russian": "Русский",
        "Chinese (Simplified)": "Китайский (упрощённый)",
        "Chinese (Traditional)": "Китайский (традиционный)",
        "French": "Французский",
        "German": "Немецкий",
        "Japanese": "Японский",
        "Arabic": "Арабский",
        "Hindi": "Хинди",
        "Italian": "Итальянский",
        "Korean": "Корейский",
        "Edit resolution": "Изменить разрешение",
        "Apply this resolution now": "Применить это разрешение сейчас",
        "Remove saved resolution": "Удалить сохранённое разрешение",
        "Remove saved resolution?": "Удалить сохранённое разрешение?",
        "Remove {details} from your saved resolutions?": "Удалить {details} из сохранённых разрешений?",
        "Remove": "Удалить",
        "On startup": "При запуске",
        "Edit Resolution": "Изменить разрешение",
        "Apply when the computer starts": "Применять при запуске компьютера",
        "Save Changes": "Сохранить изменения",
        "Save and Apply": "Сохранить и применить",
        "Cancel": "Отмена",
        "Resolution already saved": "Разрешение уже сохранено",
        "{details} is already saved for monitor {output}.": "{details} уже сохранено для монитора {output}.",
        "Apply saved": "Применить сохранённое",
        "Another saved resolution already uses these settings.": "Другая сохранённая конфигурация уже использует эти параметры.",
        "OK": "OK",
        "xrandr is not available.": "xrandr недоступен.",
    },
    "ko": {
        "Refresh monitors": "모니터 새로고침",
        "New Resolution": "새 해상도",
        "Monitor": "모니터",
        "Width": "너비",
        "Height": "높이",
        "Refresh Rate (Hz)": "주사율 (Hz)",
        "Add to System": "시스템에 추가",
        "Add and Apply": "추가 및 적용",
        "Restore default": "기본값 복원",
        "Monitor {output} restored to default resolution.": "모니터 {output}이(가) 기본 해상도로 복원되었습니다.",
        "Saved Resolutions": "저장된 해상도",
        "No saved resolutions yet.": "저장된 해상도가 없습니다.",
        "No connected monitor found.": "연결된 모니터를 찾을 수 없습니다.",
        "No monitor": "모니터 없음",
        "Select a valid monitor.": "유효한 모니터를 선택하세요.",
        "Applied on startup": "시작 시 적용",
        "Manual use": "수동 사용",
        "Language": "언어",
        "System Default": "시스템 기본값",
        "English": "영어",
        "Portuguese (Brazil)": "포르투갈어 (브라질)",
        "Spanish": "스페인어",
        "Russian": "러시아어",
        "Chinese (Simplified)": "중국어 (간체)",
        "Chinese (Traditional)": "중국어 (번체)",
        "French": "프랑스어",
        "German": "독일어",
        "Japanese": "일본어",
        "Arabic": "아랍어",
        "Hindi": "힌디어",
        "Italian": "이탈리아어",
        "Korean": "한국어",
        "Edit resolution": "해상도 편집",
        "Apply this resolution now": "지금 이 해상도 적용",
        "Remove saved resolution": "저장된 해상도 제거",
        "Remove saved resolution?": "저장된 해상도를 제거할까요?",
        "Remove {details} from your saved resolutions?": "저장된 해상도에서 {details}을(를) 제거할까요?",
        "Remove": "제거",
        "On startup": "시작 시",
        "Edit Resolution": "해상도 편집",
        "Apply when the computer starts": "컴퓨터 시작 시 적용",
        "Save Changes": "변경 사항 저장",
        "Save and Apply": "저장 및 적용",
        "Cancel": "취소",
        "Resolution already saved": "이미 저장된 해상도",
        "{details} is already saved for monitor {output}.": "{details}은(는) 모니터 {output}에 이미 저장되어 있습니다.",
        "Apply saved": "저장된 해상도 적용",
        "Another saved resolution already uses these settings.": "다른 저장된 해상도가 이미 이 설정을 사용 중입니다.",
        "OK": "확인",
        "xrandr is not available.": "xrandr을 사용할 수 없습니다.",
    },
    "de": {
        "Refresh monitors": "Monitore aktualisieren",
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "Wayland-Sitzung erkannt. LCR verwendet xrandr (X11) und funktioniert am besten unter X11 oder mit XWayland.",
        "xrandr is not available. Install xorg-xrandr on your system.": "xrandr ist nicht verfügbar. Installieren Sie xorg-xrandr auf Ihrem System.",
        "New Resolution": "Neue Auflösung",
        "Monitor": "Monitor",
        "Width": "Breite",
        "Height": "Höhe",
        "Refresh Rate (Hz)": "Bildwiederholrate (Hz)",
        "Add to System": "Zum System hinzufügen",
        "Add and Apply": "Hinzufügen und anwenden",
        "Restore default": "Standard wiederherstellen",
        "Monitor {output} restored to default resolution.": "Monitor {output} auf Standardauflösung zurückgesetzt.",
        "Saved Resolutions": "Gespeicherte Auflösungen",
        "No saved resolutions yet.": "Noch keine Auflösungen gespeichert.",
        "No connected monitor found.": "Kein angeschlossener Monitor gefunden.",
        "No monitor": "Kein Monitor",
        "Select a valid monitor.": "Wählen Sie einen gültigen Monitor aus.",
        "Resolution {details} added and applied.": "Auflösung {details} hinzugefügt und angewendet.",
        "Resolution {details} added to the system.": "Auflösung {details} zum System hinzugefügt.",
        "Resolution {details} applied.": "Auflösung {details} angewendet.",
        "Resolution not found.": "Auflösung nicht gefunden.",
        "Removed from profile, but xrandr failed: {error}": "Aus Profil entfernt, aber xrandr fehlgeschlagen: {error}",
        "Removed {details}.": "Auflösung {details} entfernt.",
        "Applied on startup": "Beim Start anwenden",
        "Manual use": "Manuelle Nutzung",
        "Language": "Sprache",
        "System Default": "Systemstandard",
        "English": "Englisch",
        "Portuguese (Brazil)": "Portugiesisch (Brasilien)",
        "Spanish": "Spanisch",
        "Russian": "Russisch",
        "Chinese (Simplified)": "Chinesisch (vereinfacht)",
        "Chinese (Traditional)": "Chinesisch (traditionell)",
        "French": "Französisch",
        "German": "Deutsch",
        "Japanese": "Japanisch",
        "Arabic": "Arabisch",
        "Hindi": "Hindi",
        "Italian": "Italienisch",
        "Korean": "Koreanisch",
        "Edit resolution": "Auflösung bearbeiten",
        "Apply this resolution now": "Diese Auflösung jetzt anwenden",
        "Remove saved resolution": "Gespeicherte Auflösung entfernen",
        "Remove saved resolution?": "Gespeicherte Auflösung entfernen?",
        "Remove {details} from your saved resolutions?": "{details} aus den gespeicherten Auflösungen entfernen?",
        "Remove": "Entfernen",
        "On startup": "Beim Start",
        "Edit Resolution": "Auflösung bearbeiten",
        "Apply when the computer starts": "Beim Computerstart anwenden",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "Wenn aktiviert, wird diese Auflösung nach Anmeldung oder Neustart automatisch ausgewählt. Wenn deaktiviert, bleibt sie gespeichert und Sie wählen selbst, wann Sie sie verwenden.",
        "Save Changes": "Änderungen speichern",
        "Save and Apply": "Speichern und anwenden",
        "Cancel": "Abbrechen",
        "Failed to update resolution: {error}": "Auflösung konnte nicht aktualisiert werden: {error}",
        "Resolution {details} updated and applied.": "Auflösung {details} aktualisiert und angewendet.",
        "Resolution {details} updated.": "Auflösung {details} aktualisiert.",
        "Resolution already saved": "Auflösung bereits gespeichert",
        "{details} is already saved for monitor {output}.": "{details} ist bereits für Monitor {output} gespeichert.",
        "Apply saved": "Gespeicherte Auflösung anwenden",
        "Another saved resolution already uses these settings.": "Eine andere gespeicherte Auflösung verwendet bereits diese Einstellungen.",
        "OK": "OK",
        "xrandr is not available.": "xrandr ist nicht verfügbar.",
    },
    "zh_CN": {
        "Refresh monitors": "刷新显示器",
        "New Resolution": "新分辨率",
        "Monitor": "显示器",
        "Width": "宽度",
        "Height": "高度",
        "Refresh Rate (Hz)": "刷新率 (Hz)",
        "Add to System": "添加到系统",
        "Add and Apply": "添加并应用",
        "Restore default": "恢复默认",
        "Monitor {output} restored to default resolution.": "显示器 {output} 已恢复为默认分辨率。",
        "Saved Resolutions": "已保存的分辨率",
        "No saved resolutions yet.": "尚无已保存的分辨率。",
        "No connected monitor found.": "未找到已连接的显示器。",
        "No monitor": "无显示器",
        "Select a valid monitor.": "请选择有效的显示器。",
        "Applied on startup": "启动时应用",
        "Manual use": "手动使用",
        "Language": "语言",
        "System Default": "系统默认",
        "English": "英语",
        "Portuguese (Brazil)": "葡萄牙语（巴西）",
        "Spanish": "西班牙语",
        "Russian": "俄语",
        "Chinese (Simplified)": "中文（简体）",
        "Chinese (Traditional)": "中文（繁体）",
        "French": "法语",
        "German": "德语",
        "Japanese": "日语",
        "Arabic": "阿拉伯语",
        "Hindi": "印地语",
        "Italian": "意大利语",
        "Korean": "韩语",
        "Edit resolution": "编辑分辨率",
        "Apply this resolution now": "立即应用此分辨率",
        "Remove saved resolution": "删除已保存的分辨率",
        "Remove saved resolution?": "删除已保存的分辨率？",
        "Remove {details} from your saved resolutions?": "从已保存的分辨率中删除 {details}？",
        "Remove": "删除",
        "On startup": "启动时",
        "Edit Resolution": "编辑分辨率",
        "Apply when the computer starts": "计算机启动时应用",
        "Save Changes": "保存更改",
        "Save and Apply": "保存并应用",
        "Cancel": "取消",
        "Resolution already saved": "分辨率已保存",
        "{details} is already saved for monitor {output}.": "{details} 已保存到显示器 {output}。",
        "Apply saved": "应用已保存的分辨率",
        "Another saved resolution already uses these settings.": "另一项已保存的分辨率已使用这些设置。",
        "OK": "确定",
        "xrandr is not available.": "xrandr 不可用。",
    },
    "zh_TW": {
        "Refresh monitors": "重新整理顯示器",
        "New Resolution": "新增解析度",
        "Monitor": "顯示器",
        "Width": "寬度",
        "Height": "高度",
        "Refresh Rate (Hz)": "更新率 (Hz)",
        "Add to System": "新增至系統",
        "Add and Apply": "新增並套用",
        "Restore default": "還原預設",
        "Monitor {output} restored to default resolution.": "顯示器 {output} 已還原為預設解析度。",
        "Saved Resolutions": "已儲存的解析度",
        "No saved resolutions yet.": "尚無已儲存的解析度。",
        "No connected monitor found.": "找不到已連接的顯示器。",
        "No monitor": "無顯示器",
        "Select a valid monitor.": "請選擇有效的顯示器。",
        "Applied on startup": "啟動時套用",
        "Manual use": "手動使用",
        "Language": "語言",
        "System Default": "系統預設",
        "English": "英語",
        "Portuguese (Brazil)": "葡萄牙語（巴西）",
        "Spanish": "西班牙語",
        "Russian": "俄語",
        "Chinese (Simplified)": "中文（簡體）",
        "Chinese (Traditional)": "中文（繁體）",
        "French": "法語",
        "German": "德語",
        "Japanese": "日語",
        "Arabic": "阿拉伯語",
        "Hindi": "印地語",
        "Italian": "義大利語",
        "Korean": "韓語",
        "Edit resolution": "編輯解析度",
        "Apply this resolution now": "立即套用此解析度",
        "Remove saved resolution": "移除已儲存的解析度",
        "Remove saved resolution?": "移除已儲存的解析度？",
        "Remove {details} from your saved resolutions?": "從已儲存的解析度中移除 {details}？",
        "Remove": "移除",
        "On startup": "啟動時",
        "Edit Resolution": "編輯解析度",
        "Apply when the computer starts": "電腦啟動時套用",
        "Save Changes": "儲存變更",
        "Save and Apply": "儲存並套用",
        "Cancel": "取消",
        "Resolution already saved": "解析度已儲存",
        "{details} is already saved for monitor {output}.": "{details} 已儲存至顯示器 {output}。",
        "Apply saved": "套用已儲存的解析度",
        "Another saved resolution already uses these settings.": "另一個已儲存的解析度已使用這些設定。",
        "OK": "確定",
        "xrandr is not available.": "xrandr 無法使用。",
    },
    "ja": {
        "Refresh monitors": "モニターを更新",
        "New Resolution": "新しい解像度",
        "Monitor": "モニター",
        "Width": "幅",
        "Height": "高さ",
        "Refresh Rate (Hz)": "リフレッシュレート (Hz)",
        "Add to System": "システムに追加",
        "Add and Apply": "追加して適用",
        "Restore default": "既定値に戻す",
        "Monitor {output} restored to default resolution.": "モニター {output} を既定の解像度に戻しました。",
        "Saved Resolutions": "保存済みの解像度",
        "No saved resolutions yet.": "保存された解像度はありません。",
        "No connected monitor found.": "接続されたモニターが見つかりません。",
        "No monitor": "モニターなし",
        "Select a valid monitor.": "有効なモニターを選択してください。",
        "Applied on startup": "起動時に適用",
        "Manual use": "手動使用",
        "Language": "言語",
        "System Default": "システムのデフォルト",
        "English": "英語",
        "Portuguese (Brazil)": "ポルトガル語 (ブラジル)",
        "Spanish": "スペイン語",
        "Russian": "ロシア語",
        "Chinese (Simplified)": "中国語 (簡体字)",
        "Chinese (Traditional)": "中国語 (繁体字)",
        "French": "フランス語",
        "German": "ドイツ語",
        "Japanese": "日本語",
        "Arabic": "アラビア語",
        "Hindi": "ヒンディー語",
        "Italian": "イタリア語",
        "Korean": "韓国語",
        "Edit resolution": "解像度を編集",
        "Apply this resolution now": "この解像度を今すぐ適用",
        "Remove saved resolution": "保存済みの解像度を削除",
        "Remove saved resolution?": "保存済みの解像度を削除しますか？",
        "Remove {details} from your saved resolutions?": "保存済みの解像度から {details} を削除しますか？",
        "Remove": "削除",
        "On startup": "起動時",
        "Edit Resolution": "解像度を編集",
        "Apply when the computer starts": "コンピューター起動時に適用",
        "Save Changes": "変更を保存",
        "Save and Apply": "保存して適用",
        "Cancel": "キャンセル",
        "Resolution already saved": "解像度は既に保存されています",
        "{details} is already saved for monitor {output}.": "{details} はモニター {output} に既に保存されています。",
        "Apply saved": "保存済みの解像度を適用",
        "Another saved resolution already uses these settings.": "別の保存済み解像度が既にこの設定を使用しています。",
        "OK": "OK",
        "xrandr is not available.": "xrandr が利用できません。",
    },
    "ar": {
        "Refresh monitors": "تحديث الشاشات",
        "New Resolution": "دقة جديدة",
        "Monitor": "الشاشة",
        "Width": "العرض",
        "Height": "الارتفاع",
        "Refresh Rate (Hz)": "معدل التحديث (هرتز)",
        "Add to System": "إضافة إلى النظام",
        "Add and Apply": "إضافة وتطبيق",
        "Restore default": "استعادة الافتراضي",
        "Monitor {output} restored to default resolution.": "تمت استعادة الشاشة {output} إلى الدقة الافتراضية.",
        "Saved Resolutions": "الدقات المحفوظة",
        "No saved resolutions yet.": "لا توجد دقات محفوظة.",
        "No connected monitor found.": "لم يتم العثور على شاشة متصلة.",
        "No monitor": "لا توجد شاشة",
        "Select a valid monitor.": "اختر شاشة صالحة.",
        "Applied on startup": "تُطبَّق عند بدء التشغيل",
        "Manual use": "استخدام يدوي",
        "Language": "اللغة",
        "System Default": "افتراضي النظام",
        "English": "الإنجليزية",
        "Portuguese (Brazil)": "البرتغالية (البرازيل)",
        "Spanish": "الإسبانية",
        "Russian": "الروسية",
        "Chinese (Simplified)": "الصينية (المبسّطة)",
        "Chinese (Traditional)": "الصينية (التقليدية)",
        "French": "الفرنسية",
        "German": "الألمانية",
        "Japanese": "اليابانية",
        "Arabic": "العربية",
        "Hindi": "الهندية",
        "Italian": "الإيطالية",
        "Korean": "الكورية",
        "Edit resolution": "تعديل الدقة",
        "Apply this resolution now": "تطبيق هذه الدقة الآن",
        "Remove saved resolution": "إزالة الدقة المحفوظة",
        "Remove saved resolution?": "إزالة الدقة المحفوظة؟",
        "Remove {details} from your saved resolutions?": "إزالة {details} من الدقات المحفوظة؟",
        "Remove": "إزالة",
        "On startup": "عند بدء التشغيل",
        "Edit Resolution": "تعديل الدقة",
        "Apply when the computer starts": "تطبيق عند بدء تشغيل الحاسوب",
        "Save Changes": "حفظ التغييرات",
        "Save and Apply": "حفظ وتطبيق",
        "Cancel": "إلغاء",
        "Resolution already saved": "الدقة محفوظة بالفعل",
        "{details} is already saved for monitor {output}.": "{details} محفوظة بالفعل للشاشة {output}.",
        "Apply saved": "تطبيق الدقة المحفوظة",
        "Another saved resolution already uses these settings.": "دقة محفوظة أخرى تستخدم هذه الإعدادات بالفعل.",
        "OK": "موافق",
        "xrandr is not available.": "xrandr غير متاح.",
    },
    "hi": {
        "Refresh monitors": "मॉनिटर रीफ़्रेश करें",
        "New Resolution": "नया रिज़ॉल्यूशन",
        "Monitor": "मॉनिटर",
        "Width": "चौड़ाई",
        "Height": "ऊँचाई",
        "Refresh Rate (Hz)": "रीफ़्रेश दर (Hz)",
        "Add to System": "सिस्टम में जोड़ें",
        "Add and Apply": "जोड़ें और लागू करें",
        "Restore default": "डिफ़ॉल्ट पुनर्स्थापित करें",
        "Monitor {output} restored to default resolution.": "मॉनिटर {output} डिफ़ॉल्ट रिज़ॉल्यूशन पर पुनर्स्थापित।",
        "Saved Resolutions": "सहेजे गए रिज़ॉल्यूशन",
        "No saved resolutions yet.": "अभी कोई रिज़ॉल्यूशन सहेजा नहीं गया।",
        "No connected monitor found.": "कोई कनेक्टेड मॉनिटर नहीं मिला।",
        "No monitor": "कोई मॉनिटर नहीं",
        "Select a valid monitor.": "एक वैध मॉनिटर चुनें।",
        "Applied on startup": "स्टार्टअप पर लागू",
        "Manual use": "मैन्युअल उपयोग",
        "Language": "भाषा",
        "System Default": "सिस्टम डिफ़ॉल्ट",
        "English": "अंग्रेज़ी",
        "Portuguese (Brazil)": "पुर्तगाली (ब्राज़ील)",
        "Spanish": "स्पेनिश",
        "Russian": "रूसी",
        "Chinese (Simplified)": "चीनी (सरलीकृत)",
        "Chinese (Traditional)": "चीनी (पारंपरिक)",
        "French": "फ़्रेंच",
        "German": "जर्मन",
        "Japanese": "जापानी",
        "Arabic": "अरबी",
        "Hindi": "हिन्दी",
        "Italian": "इतालवी",
        "Korean": "कोरियाई",
        "Edit resolution": "रिज़ॉल्यूशन संपादित करें",
        "Apply this resolution now": "यह रिज़ॉल्यूशन अभी लागू करें",
        "Remove saved resolution": "सहेजा रिज़ॉल्यूशन हटाएँ",
        "Remove saved resolution?": "सहेजा रिज़ॉल्यूशन हटाएँ?",
        "Remove {details} from your saved resolutions?": "सहेजे रिज़ॉल्यूशन से {details} हटाएँ?",
        "Remove": "हटाएँ",
        "On startup": "स्टार्टअप पर",
        "Edit Resolution": "रिज़ॉल्यूशन संपादित करें",
        "Apply when the computer starts": "कंप्यूटर शुरू होने पर लागू करें",
        "Save Changes": "परिवर्तन सहेजें",
        "Save and Apply": "सहेजें और लागू करें",
        "Cancel": "रद्द करें",
        "Resolution already saved": "रिज़ॉल्यूशन पहले से सहेजा है",
        "{details} is already saved for monitor {output}.": "{details} मॉनिटर {output} के लिए पहले से सहेजा है।",
        "Apply saved": "सहेजा रिज़ॉल्यूशन लागू करें",
        "Another saved resolution already uses these settings.": "कोई अन्य सहेजा रिज़ॉल्यूशन पहले से ये सेटिंग्स उपयोग कर रहा है।",
        "OK": "ठीक है",
        "xrandr is not available.": "xrandr उपलब्ध नहीं है।",
    },
    "it": {
        "Refresh monitors": "Aggiorna monitor",
        "New Resolution": "Nuova risoluzione",
        "Monitor": "Monitor",
        "Width": "Larghezza",
        "Height": "Altezza",
        "Refresh Rate (Hz)": "Frequenza (Hz)",
        "Add to System": "Aggiungi al sistema",
        "Add and Apply": "Aggiungi e applica",
        "Restore default": "Ripristina predefinito",
        "Monitor {output} restored to default resolution.": "Monitor {output} ripristinato alla risoluzione predefinita.",
        "Saved Resolutions": "Risoluzioni salvate",
        "No saved resolutions yet.": "Nessuna risoluzione salvata.",
        "No connected monitor found.": "Nessun monitor connesso trovato.",
        "No monitor": "Nessun monitor",
        "Select a valid monitor.": "Seleziona un monitor valido.",
        "Applied on startup": "Applicata all'avvio",
        "Manual use": "Uso manuale",
        "Language": "Lingua",
        "System Default": "Predefinito di sistema",
        "English": "Inglese",
        "Portuguese (Brazil)": "Portoghese (Brasile)",
        "Spanish": "Spagnolo",
        "Russian": "Russo",
        "Chinese (Simplified)": "Cinese (semplificato)",
        "Chinese (Traditional)": "Cinese (tradizionale)",
        "French": "Francese",
        "German": "Tedesco",
        "Japanese": "Giapponese",
        "Arabic": "Arabo",
        "Hindi": "Hindi",
        "Italian": "Italiano",
        "Korean": "Coreano",
        "Edit resolution": "Modifica risoluzione",
        "Apply this resolution now": "Applica questa risoluzione ora",
        "Remove saved resolution": "Rimuovi risoluzione salvata",
        "Remove saved resolution?": "Rimuovere la risoluzione salvata?",
        "Remove {details} from your saved resolutions?": "Rimuovere {details} dalle risoluzioni salvate?",
        "Remove": "Rimuovi",
        "On startup": "All'avvio",
        "Edit Resolution": "Modifica risoluzione",
        "Apply when the computer starts": "Applica all'avvio del computer",
        "Save Changes": "Salva modifiche",
        "Save and Apply": "Salva e applica",
        "Cancel": "Annulla",
        "Resolution already saved": "Risoluzione già salvata",
        "{details} is already saved for monitor {output}.": "{details} è già salvata per il monitor {output}.",
        "Apply saved": "Applica risoluzione salvata",
        "Another saved resolution already uses these settings.": "Un'altra risoluzione salvata usa già queste impostazioni.",
        "OK": "OK",
        "xrandr is not available.": "xrandr non è disponibile.",
    },
}

# Mensagens de resolução / Wayland ausentes em vários catálogos.
CORE_EXTRA_TRANSLATIONS: dict[str, dict[str, str]] = {
    "es": {
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "Sesión Wayland detectada. LCR usa xrandr (X11) y funciona mejor en sesiones X11 o cuando el compositor expone XWayland.",
        "xrandr is not available. Install xorg-xrandr on your system.": "xrandr no está disponible. Instale xorg-xrandr en el sistema.",
        "Resolution {details} added and applied.": "Resolución {details} añadida y aplicada.",
        "Resolution {details} added to the system.": "Resolución {details} añadida al sistema.",
        "Resolution {details} applied.": "Resolución {details} aplicada.",
        "Resolution not found.": "Resolución no encontrada.",
        "Removed from profile, but xrandr failed: {error}": "Eliminada del perfil, pero xrandr falló: {error}",
        "Removed {details}.": "Resolución {details} eliminada.",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "Si está activada, esta resolución se selecciona automáticamente al iniciar sesión o reiniciar. Si está desactivada, permanece guardada y usted decide cuándo usarla.",
        "Failed to update resolution: {error}": "Error al actualizar la resolución: {error}",
        "Resolution {details} updated and applied.": "Resolución {details} actualizada y aplicada.",
        "Resolution {details} updated.": "Resolución {details} actualizada.",
    },
    "ru": {
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "Обнаружена сессия Wayland. LCR использует xrandr (X11) и лучше всего работает в сессиях X11 или когда композитор предоставляет XWayland.",
        "xrandr is not available. Install xorg-xrandr on your system.": "xrandr недоступен. Установите пакет xorg-xrandr в системе.",
        "Resolution {details} added and applied.": "Разрешение {details} добавлено и применено.",
        "Resolution {details} added to the system.": "Разрешение {details} добавлено в систему.",
        "Resolution {details} applied.": "Разрешение {details} применено.",
        "Resolution not found.": "Разрешение не найдено.",
        "Removed from profile, but xrandr failed: {error}": "Удалено из профиля, но xrandr завершился с ошибкой: {error}",
        "Removed {details}.": "Разрешение {details} удалено.",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "Если включено, это разрешение выбирается автоматически после входа или перезагрузки. Если выключено, оно остаётся сохранённым, и вы сами выбираете, когда его использовать.",
        "Failed to update resolution: {error}": "Не удалось обновить разрешение: {error}",
        "Resolution {details} updated and applied.": "Разрешение {details} обновлено и применено.",
        "Resolution {details} updated.": "Разрешение {details} обновлено.",
        "OK": "ОК",
    },
    "ko": {
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "Wayland 세션이 감지되었습니다. LCR은 xrandr(X11)을 사용하며 X11 세션이나 컴포지터가 XWayland를 제공할 때 가장 잘 작동합니다.",
        "xrandr is not available. Install xorg-xrandr on your system.": "xrandr을 사용할 수 없습니다. 시스템에 xorg-xrandr을 설치하세요.",
        "Resolution {details} added and applied.": "해상도 {details}이(가) 추가되어 적용되었습니다.",
        "Resolution {details} added to the system.": "해상도 {details}이(가) 시스템에 추가되었습니다.",
        "Resolution {details} applied.": "해상도 {details}이(가) 적용되었습니다.",
        "Resolution not found.": "해상도를 찾을 수 없습니다.",
        "Removed from profile, but xrandr failed: {error}": "프로필에서 제거되었지만 xrandr이 실패했습니다: {error}",
        "Removed {details}.": "해상도 {details}이(가) 제거되었습니다.",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "활성화하면 로그인 또는 재시작 후 이 해상도가 자동으로 선택됩니다. 비활성화하면 저장된 상태로 유지되며 사용 시점을 직접 선택합니다.",
        "Failed to update resolution: {error}": "해상도 업데이트 실패: {error}",
        "Resolution {details} updated and applied.": "해상도 {details}이(가) 업데이트되어 적용되었습니다.",
        "Resolution {details} updated.": "해상도 {details}이(가) 업데이트되었습니다.",
    },
    "zh_CN": {
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "检测到 Wayland 会话。LCR 使用 xrandr (X11)，在 X11 会话或合成器提供 XWayland 时效果最佳。",
        "xrandr is not available. Install xorg-xrandr on your system.": "xrandr 不可用。请在系统上安装 xorg-xrandr。",
        "Resolution {details} added and applied.": "分辨率 {details} 已添加并应用。",
        "Resolution {details} added to the system.": "分辨率 {details} 已添加到系统。",
        "Resolution {details} applied.": "分辨率 {details} 已应用。",
        "Resolution not found.": "未找到分辨率。",
        "Removed from profile, but xrandr failed: {error}": "已从配置文件中移除，但 xrandr 失败：{error}",
        "Removed {details}.": "已移除 {details}。",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "启用后，登录或重启后将自动选择此分辨率。禁用后仍保留在列表中，由您自行选择何时使用。",
        "Failed to update resolution: {error}": "更新分辨率失败：{error}",
        "Resolution {details} updated and applied.": "分辨率 {details} 已更新并应用。",
        "Resolution {details} updated.": "分辨率 {details} 已更新。",
    },
    "zh_TW": {
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "偵測到 Wayland 工作階段。LCR 使用 xrandr (X11)，在 X11 工作階段或合成器提供 XWayland 時效果最佳。",
        "xrandr is not available. Install xorg-xrandr on your system.": "xrandr 無法使用。請在系統上安裝 xorg-xrandr。",
        "Resolution {details} added and applied.": "解析度 {details} 已新增並套用。",
        "Resolution {details} added to the system.": "解析度 {details} 已新增至系統。",
        "Resolution {details} applied.": "解析度 {details} 已套用。",
        "Resolution not found.": "找不到解析度。",
        "Removed from profile, but xrandr failed: {error}": "已從設定檔移除，但 xrandr 失敗：{error}",
        "Removed {details}.": "已移除 {details}。",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "啟用後，登入或重新啟動後將自動選取此解析度。停用後仍保留在清單中，由您自行選擇何時使用。",
        "Failed to update resolution: {error}": "更新解析度失敗：{error}",
        "Resolution {details} updated and applied.": "解析度 {details} 已更新並套用。",
        "Resolution {details} updated.": "解析度 {details} 已更新。",
    },
    "ja": {
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "Wayland セッションを検出しました。LCR は xrandr (X11) を使用し、X11 セッションまたはコンポジターが XWayland を提供する場合に最適に動作します。",
        "xrandr is not available. Install xorg-xrandr on your system.": "xrandr が利用できません。システムに xorg-xrandr をインストールしてください。",
        "Resolution {details} added and applied.": "解像度 {details} を追加して適用しました。",
        "Resolution {details} added to the system.": "解像度 {details} をシステムに追加しました。",
        "Resolution {details} applied.": "解像度 {details} を適用しました。",
        "Resolution not found.": "解像度が見つかりません。",
        "Removed from profile, but xrandr failed: {error}": "プロファイルから削除しましたが、xrandr が失敗しました: {error}",
        "Removed {details}.": "解像度 {details} を削除しました。",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "有効にすると、ログインまたは再起動後にこの解像度が自動的に選択されます。無効の場合は保存されたままとなり、使用するタイミングはご自身で選べます。",
        "Failed to update resolution: {error}": "解像度の更新に失敗しました: {error}",
        "Resolution {details} updated and applied.": "解像度 {details} を更新して適用しました。",
        "Resolution {details} updated.": "解像度 {details} を更新しました。",
    },
    "ar": {
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "تم اكتشاف جلسة Wayland. يستخدم LCR أداة xrandr (X11) ويعمل بشكل أفضل في جلسات X11 أو عندما يوفّر المُجمِّع XWayland.",
        "xrandr is not available. Install xorg-xrandr on your system.": "xrandr غير متاح. ثبّت الحزمة xorg-xrandr على نظامك.",
        "Resolution {details} added and applied.": "تمت إضافة الدقة {details} وتطبيقها.",
        "Resolution {details} added to the system.": "تمت إضافة الدقة {details} إلى النظام.",
        "Resolution {details} applied.": "تم تطبيق الدقة {details}.",
        "Resolution not found.": "الدقة غير موجودة.",
        "Removed from profile, but xrandr failed: {error}": "أُزيلت من الملف الشخصي، لكن xrandr فشل: {error}",
        "Removed {details}.": "تمت إزالة {details}.",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "إذا كان مفعّلاً، تُختار هذه الدقة تلقائياً بعد تسجيل الدخول أو إعادة التشغيل. إذا كان معطّلاً، تبقى محفوظة وتختار متى تستخدمها.",
        "Failed to update resolution: {error}": "فشل تحديث الدقة: {error}",
        "Resolution {details} updated and applied.": "تم تحديث الدقة {details} وتطبيقها.",
        "Resolution {details} updated.": "تم تحديث الدقة {details}.",
    },
    "hi": {
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "Wayland सत्र मिला। LCR xrandr (X11) उपयोग करता है और X11 सत्र या जब कम्पोज़र XWayland देता है तब सबसे अच्छा काम करता है।",
        "xrandr is not available. Install xorg-xrandr on your system.": "xrandr उपलब्ध नहीं है। अपने सिस्टम पर xorg-xrandr इंस्टॉल करें।",
        "Resolution {details} added and applied.": "रिज़ॉल्यूशन {details} जोड़ा और लागू किया गया।",
        "Resolution {details} added to the system.": "रिज़ॉल्यूशन {details} सिस्टम में जोड़ा गया।",
        "Resolution {details} applied.": "रिज़ॉल्यूशन {details} लागू किया गया।",
        "Resolution not found.": "रिज़ॉल्यूशन नहीं मिला।",
        "Removed from profile, but xrandr failed: {error}": "प्रोफ़ाइल से हटाया, लेकिन xrandr विफल: {error}",
        "Removed {details}.": "{details} हटाया गया।",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "सक्षम होने पर, लॉगिन या पुनरारंभ के बाद यह रिज़ॉल्यूशन स्वचालित रूप से चुना जाता है। अक्षम होने पर, यह सहेजा रहता है और आप उपयोग का समय चुनते हैं।",
        "Failed to update resolution: {error}": "रिज़ॉल्यूशन अपडेट विफल: {error}",
        "Resolution {details} updated and applied.": "रिज़ॉल्यूशन {details} अपडेट और लागू किया गया।",
        "Resolution {details} updated.": "रिज़ॉल्यूशन {details} अपडेट किया गया।",
    },
    "it": {
        "Wayland session detected. LCR uses xrandr (X11) and works best on X11 sessions or when the compositor exposes XWayland.": "Sessione Wayland rilevata. LCR usa xrandr (X11) e funziona meglio in sessioni X11 o quando il compositor espone XWayland.",
        "xrandr is not available. Install xorg-xrandr on your system.": "xrandr non è disponibile. Installa xorg-xrandr sul sistema.",
        "Resolution {details} added and applied.": "Risoluzione {details} aggiunta e applicata.",
        "Resolution {details} added to the system.": "Risoluzione {details} aggiunta al sistema.",
        "Resolution {details} applied.": "Risoluzione {details} applicata.",
        "Resolution not found.": "Risoluzione non trovata.",
        "Removed from profile, but xrandr failed: {error}": "Rimossa dal profilo, ma xrandr non è riuscito: {error}",
        "Removed {details}.": "Risoluzione {details} rimossa.",
        "If enabled, this resolution is selected automatically after you log in or restart. If disabled, it remains saved and you choose when to use it.": "Se abilitata, questa risoluzione viene selezionata automaticamente dopo l'accesso o il riavvio. Se disabilitata, resta salvata e scegli tu quando usarla.",
        "Failed to update resolution: {error}": "Impossibile aggiornare la risoluzione: {error}",
        "Resolution {details} updated and applied.": "Risoluzione {details} aggiornata e applicata.",
        "Resolution {details} updated.": "Risoluzione {details} aggiornata.",
    },
}


NEW_UI_TRANSLATIONS: dict[str, dict[str, str]] = {
    "pt_BR": {
        "Supported resolutions": "Resoluções suportadas",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "Modos reportados pelo xrandr para {output}. TVs e alguns monitores só aceitam estes — modos personalizados podem falhar.",
        "No modes reported for this display.": "Nenhum modo reportado para esta saída.",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Hz",
        " (active: {rate:g} Hz)": " (ativa: {rate:g} Hz)",
        "{rates} Hz": "{rates} Hz",
        " · active: {rate:g} Hz": " · ativa: {rate:g} Hz",
        "Use": "Usar",
        "Close": "Fechar",
        "Apply now": "Aplicar agora",
        "Fill form fields": "Preencher formulário",
        "Current": "Atual",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "Dica: use ▶ para aplicar um modo agora. Use o botão copiar para preencher o formulário.",
        "({count} supported modes)": "({count} modos suportados)",
        "Fields filled with {details}.": "Campos preenchidos com {details}.",
        "Added and applied.": "Adicionada e aplicada.",
        "Added to the system.": "Adicionada ao sistema.",
        "Applied.": "Aplicada.",
        "Updated and applied.": "Atualizada e aplicada.",
        "Updated.": "Atualizada.",
        "Removed.": "Removida.",
        "Fields filled.": "Campos preenchidos.",
        "Saved resolutions for {output}": "Resoluções salvas — {output}",
        "No saved resolutions for this monitor.": "Nenhuma resolução salva para este monitor.",
    },
    "fr": {
        "Supported resolutions": "Résolutions prises en charge",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "Modes signalés par xrandr pour {output}. Les téléviseurs et certains moniteurs n'acceptent que ceux-ci — les modes personnalisés peuvent échouer.",
        "No modes reported for this display.": "Aucun mode signalé pour cet écran.",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Hz",
        " (active: {rate:g} Hz)": " (active : {rate:g} Hz)",
        "{rates} Hz": "{rates} Hz",
        " · active: {rate:g} Hz": " · active : {rate:g} Hz",
        "Use": "Utiliser",
        "Close": "Fermer",
        "Apply now": "Appliquer maintenant",
        "Fill form fields": "Remplir le formulaire",
        "Current": "Actuelle",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "Astuce : utilisez ▶ pour appliquer un mode. Utilisez le bouton copier pour remplir le formulaire.",
        "({count} supported modes)": "({count} modes pris en charge)",
        "Fields filled with {details}.": "Champs remplis avec {details}.",
        "Added and applied.": "Ajoutée et appliquée.",
        "Added to the system.": "Ajoutée au système.",
        "Applied.": "Appliquée.",
        "Updated and applied.": "Mise à jour et appliquée.",
        "Updated.": "Mise à jour.",
        "Removed.": "Supprimée.",
        "Fields filled.": "Champs remplis.",
        "Saved resolutions for {output}": "Résolutions enregistrées — {output}",
        "No saved resolutions for this monitor.": "Aucune résolution enregistrée pour ce moniteur.",
    },
    "es": {
        "Supported resolutions": "Resoluciones compatibles",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "Modos informados por xrandr para {output}. Las TV y algunos monitores solo aceptan estos — los modos personalizados pueden fallar.",
        "No modes reported for this display.": "No se informó ningún modo para esta pantalla.",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Hz",
        " (active: {rate:g} Hz)": " (activa: {rate:g} Hz)",
        "{rates} Hz": "{rates} Hz",
        " · active: {rate:g} Hz": " · activa: {rate:g} Hz",
        "Use": "Usar",
        "Close": "Cerrar",
        "Apply now": "Aplicar ahora",
        "Fill form fields": "Rellenar formulario",
        "Current": "Actual",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "Consejo: use ▶ para aplicar un modo ahora. Use el botón copiar para rellenar el formulario.",
        "({count} supported modes)": "({count} modos compatibles)",
        "Fields filled with {details}.": "Campos rellenados con {details}.",
        "Added and applied.": "Añadida y aplicada.",
        "Added to the system.": "Añadida al sistema.",
        "Applied.": "Aplicada.",
        "Updated and applied.": "Actualizada y aplicada.",
        "Updated.": "Actualizada.",
        "Removed.": "Eliminada.",
        "Fields filled.": "Campos rellenados.",
        "Saved resolutions for {output}": "Resoluciones guardadas — {output}",
        "No saved resolutions for this monitor.": "No hay resoluciones guardadas para este monitor.",
    },
    "ru": {
        "Supported resolutions": "Поддерживаемые разрешения",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "Режимы xrandr для {output}. Телевизоры и некоторые мониторы принимают только их — пользовательские режимы могут не работать.",
        "No modes reported for this display.": "Для этого экрана режимы не сообщены.",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Гц",
        " (active: {rate:g} Hz)": " (активно: {rate:g} Гц)",
        "{rates} Hz": "{rates} Гц",
        " · active: {rate:g} Hz": " · активно: {rate:g} Гц",
        "Use": "Использовать",
        "Close": "Закрыть",
        "Apply now": "Применить сейчас",
        "Fill form fields": "Заполнить форму",
        "Current": "Текущая",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "Подсказка: нажмите ▶, чтобы применить режим. Кнопка копирования заполнит форму.",
        "({count} supported modes)": "({count} поддерживаемых режимов)",
        "Fields filled with {details}.": "Поля заполнены: {details}.",
        "Added and applied.": "Добавлено и применено.",
        "Added to the system.": "Добавлено в систему.",
        "Applied.": "Применено.",
        "Updated and applied.": "Обновлено и применено.",
        "Updated.": "Обновлено.",
        "Removed.": "Удалено.",
        "Fields filled.": "Поля заполнены.",
        "Saved resolutions for {output}": "Сохранённые разрешения — {output}",
        "No saved resolutions for this monitor.": "Нет сохранённых разрешений для этого монитора.",
    },
    "ko": {
        "Supported resolutions": "지원되는 해상도",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "xrandr가 {output}에 대해 보고한 모드입니다. TV와 일부 모니터는 이 모드만 허용하며 사용자 지정 모드는 실패할 수 있습니다.",
        "No modes reported for this display.": "이 디스플레이에 보고된 모드가 없습니다.",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Hz",
        " (active: {rate:g} Hz)": " (활성: {rate:g} Hz)",
        "{rates} Hz": "{rates} Hz",
        " · active: {rate:g} Hz": " · 활성: {rate:g} Hz",
        "Use": "사용",
        "Close": "닫기",
        "Apply now": "지금 적용",
        "Fill form fields": "양식 채우기",
        "Current": "현재",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "팁: ▶로 지금 모드를 적용하세요. 복사 버튼으로 양식을 채우세요.",
        "({count} supported modes)": "({count}개 지원 모드)",
        "Fields filled with {details}.": "양식이 {details}(으)로 채워졌습니다.",
        "Added and applied.": "추가 및 적용됨.",
        "Added to the system.": "시스템에 추가됨.",
        "Applied.": "적용됨.",
        "Updated and applied.": "업데이트 및 적용됨.",
        "Updated.": "업데이트됨.",
        "Removed.": "제거됨.",
        "Fields filled.": "양식 채움.",
        "Saved resolutions for {output}": "저장된 해상도 — {output}",
        "No saved resolutions for this monitor.": "이 모니터에 저장된 해상도가 없습니다.",
    },
    "de": {
        "Supported resolutions": "Unterstützte Auflösungen",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "Von xrandr für {output} gemeldete Modi. TVs und manche Monitore akzeptieren nur diese — benutzerdefinierte Modi können fehlschlagen.",
        "No modes reported for this display.": "Keine Modi für diese Anzeige gemeldet.",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Hz",
        " (active: {rate:g} Hz)": " (aktiv: {rate:g} Hz)",
        "{rates} Hz": "{rates} Hz",
        " · active: {rate:g} Hz": " · aktiv: {rate:g} Hz",
        "Use": "Verwenden",
        "Close": "Schließen",
        "Apply now": "Jetzt anwenden",
        "Fill form fields": "Formular ausfüllen",
        "Current": "Aktuell",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "Tipp: Mit ▶ Modus jetzt anwenden. Mit Kopieren das Formular ausfüllen.",
        "({count} supported modes)": "({count} unterstützte Modi)",
        "Fields filled with {details}.": "Felder ausgefüllt mit {details}.",
        "Added and applied.": "Hinzugefügt und angewendet.",
        "Added to the system.": "Zum System hinzugefügt.",
        "Applied.": "Angewendet.",
        "Updated and applied.": "Aktualisiert und angewendet.",
        "Updated.": "Aktualisiert.",
        "Removed.": "Entfernt.",
        "Fields filled.": "Felder ausgefüllt.",
        "Saved resolutions for {output}": "Gespeicherte Auflösungen — {output}",
        "No saved resolutions for this monitor.": "Keine gespeicherten Auflösungen für diesen Monitor.",
    },
    "zh_CN": {
        "Supported resolutions": "支持的分辨率",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "xrandr 为 {output} 报告的模式。电视和部分显示器仅接受这些模式 — 自定义模式可能失败。",
        "No modes reported for this display.": "此显示器未报告任何模式。",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Hz",
        " (active: {rate:g} Hz)": "（当前：{rate:g} Hz）",
        "{rates} Hz": "{rates} Hz",
        " · active: {rate:g} Hz": " · 当前：{rate:g} Hz",
        "Use": "使用",
        "Close": "关闭",
        "Apply now": "立即应用",
        "Fill form fields": "填充表单",
        "Current": "当前",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "提示：使用 ▶ 立即应用模式。使用复制按钮填充表单。",
        "({count} supported modes)": "（{count} 个支持的模式）",
        "Fields filled with {details}.": "已填入 {details}。",
        "Added and applied.": "已添加并应用。",
        "Added to the system.": "已添加到系统。",
        "Applied.": "已应用。",
        "Updated and applied.": "已更新并应用。",
        "Updated.": "已更新。",
        "Removed.": "已移除。",
        "Fields filled.": "已填充表单。",
        "Saved resolutions for {output}": "已保存的分辨率 — {output}",
        "No saved resolutions for this monitor.": "此显示器没有已保存的分辨率。",
    },
    "zh_TW": {
        "Supported resolutions": "支援的解析度",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "xrandr 為 {output} 回報的模式。電視和部分螢幕僅接受這些模式 — 自訂模式可能失敗。",
        "No modes reported for this display.": "此螢幕未回報任何模式。",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Hz",
        " (active: {rate:g} Hz)": "（使用中：{rate:g} Hz）",
        "{rates} Hz": "{rates} Hz",
        " · active: {rate:g} Hz": " · 使用中：{rate:g} Hz",
        "Use": "使用",
        "Close": "關閉",
        "Apply now": "立即套用",
        "Fill form fields": "填入表單",
        "Current": "目前",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "提示：使用 ▶ 立即套用模式。使用複製按鈕填入表單。",
        "({count} supported modes)": "（{count} 個支援的模式）",
        "Fields filled with {details}.": "已填入 {details}。",
        "Added and applied.": "已新增並套用。",
        "Added to the system.": "已新增至系統。",
        "Applied.": "已套用。",
        "Updated and applied.": "已更新並套用。",
        "Updated.": "已更新。",
        "Removed.": "已移除。",
        "Fields filled.": "已填入表單。",
        "Saved resolutions for {output}": "已儲存的解析度 — {output}",
        "No saved resolutions for this monitor.": "此螢幕沒有已儲存的解析度。",
    },
    "ja": {
        "Supported resolutions": "サポートされている解像度",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "xrandr が {output} に報告したモードです。TV や一部のモニターはこれらのみ受け付け、カスタムモードは失敗することがあります。",
        "No modes reported for this display.": "このディスプレイに報告されたモードはありません。",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Hz",
        " (active: {rate:g} Hz)": "（使用中: {rate:g} Hz）",
        "{rates} Hz": "{rates} Hz",
        " · active: {rate:g} Hz": " · 使用中: {rate:g} Hz",
        "Use": "使用",
        "Close": "閉じる",
        "Apply now": "今すぐ適用",
        "Fill form fields": "フォームに入力",
        "Current": "使用中",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "ヒント: ▶ でモードを今すぐ適用。コピーボタンでフォームに入力。",
        "({count} supported modes)": "（{count} 件のサポートモード）",
        "Fields filled with {details}.": "フォームに {details} を入力しました。",
        "Added and applied.": "追加して適用しました。",
        "Added to the system.": "システムに追加しました。",
        "Applied.": "適用しました。",
        "Updated and applied.": "更新して適用しました。",
        "Updated.": "更新しました。",
        "Removed.": "削除しました。",
        "Fields filled.": "フォームに入力しました。",
        "Saved resolutions for {output}": "保存済み解像度 — {output}",
        "No saved resolutions for this monitor.": "このモニターに保存された解像度はありません。",
    },
    "ar": {
        "Supported resolutions": "الدقات المدعومة",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "أوضاع xrandr لـ {output}. تدعم التلفزيات وبعض الشاشات هذه فقط — قد تفشل الأوضاع المخصصة.",
        "No modes reported for this display.": "لا توجد أوضاع مُبلّغ عنها لهذه الشاشة.",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Hz",
        " (active: {rate:g} Hz)": " (نشط: {rate:g} Hz)",
        "{rates} Hz": "{rates} Hz",
        " · active: {rate:g} Hz": " · نشط: {rate:g} Hz",
        "Use": "استخدام",
        "Close": "إغلاق",
        "Apply now": "تطبيق الآن",
        "Fill form fields": "ملء النموذج",
        "Current": "الحالي",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "نصيحة: استخدم ▶ لتطبيق الوضع الآن. استخدم زر النسخ لملء النموذج.",
        "({count} supported modes)": "({count} أوضاع مدعومة)",
        "Fields filled with {details}.": "تم ملء الحقول بـ {details}.",
        "Added and applied.": "تمت الإضافة والتطبيق.",
        "Added to the system.": "تمت الإضافة إلى النظام.",
        "Applied.": "تم التطبيق.",
        "Updated and applied.": "تم التحديث والتطبيق.",
        "Updated.": "تم التحديث.",
        "Removed.": "تمت الإزالة.",
        "Fields filled.": "تم ملء النموذج.",
        "Saved resolutions for {output}": "الدقات المحفوظة — {output}",
        "No saved resolutions for this monitor.": "لا توجد دقات محفوظة لهذه الشاشة.",
    },
    "hi": {
        "Supported resolutions": "समर्थित रिज़ॉल्यूशन",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "xrandr द्वारा {output} के लिए रिपोर्ट किए गए मोड। TV और कुछ मॉनिटर केवल इन्हीं को स्वीकार करते हैं — कस्टम मोड विफल हो सकते हैं।",
        "No modes reported for this display.": "इस डिस्प्ले के लिए कोई मोड रिपोर्ट नहीं किया गया।",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Hz",
        " (active: {rate:g} Hz)": " (सक्रिय: {rate:g} Hz)",
        "{rates} Hz": "{rates} Hz",
        " · active: {rate:g} Hz": " · सक्रिय: {rate:g} Hz",
        "Use": "उपयोग करें",
        "Close": "बंद करें",
        "Apply now": "अभी लागू करें",
        "Fill form fields": "फ़ॉर्म भरें",
        "Current": "वर्तमान",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "सुझाव: ▶ से अभी मोड लागू करें। फ़ॉर्म भरने के लिए कॉपी बटन का उपयोग करें।",
        "({count} supported modes)": "({count} समर्थित मोड)",
        "Fields filled with {details}.": "फ़ॉर्म {details} से भरा गया।",
        "Added and applied.": "जोड़ा और लागू किया।",
        "Added to the system.": "सिस्टम में जोड़ा।",
        "Applied.": "लागू किया।",
        "Updated and applied.": "अपडेट और लागू किया।",
        "Updated.": "अपडेट किया।",
        "Removed.": "हटाया।",
        "Fields filled.": "फ़ॉर्म भरा।",
        "Saved resolutions for {output}": "सहेजे गए रिज़ॉल्यूशन — {output}",
        "No saved resolutions for this monitor.": "इस मॉनिटर के लिए कोई सहेजा रिज़ॉल्यूशन नहीं।",
    },
    "it": {
        "Supported resolutions": "Risoluzioni supportate",
        "Modes reported by xrandr for {output}. TVs and some monitors only accept these — custom modes may fail.": "Modalità segnalate da xrandr per {output}. TV e alcuni monitor accettano solo queste — le modalità personalizzate possono fallire.",
        "No modes reported for this display.": "Nessuna modalità segnalata per questo schermo.",
        "{resolution} — {rates} Hz": "{resolution} — {rates} Hz",
        " (active: {rate:g} Hz)": " (attiva: {rate:g} Hz)",
        "{rates} Hz": "{rates} Hz",
        " · active: {rate:g} Hz": " · attiva: {rate:g} Hz",
        "Use": "Usa",
        "Close": "Chiudi",
        "Apply now": "Applica ora",
        "Fill form fields": "Compila modulo",
        "Current": "Attuale",
        "Tip: use ▶ to apply a mode now. Use the copy button to fill the form.": "Suggerimento: usa ▶ per applicare una modalità ora. Usa copia per compilare il modulo.",
        "({count} supported modes)": "({count} modalità supportate)",
        "Fields filled with {details}.": "Campi compilati con {details}.",
        "Added and applied.": "Aggiunta e applicata.",
        "Added to the system.": "Aggiunta al sistema.",
        "Applied.": "Applicata.",
        "Updated and applied.": "Aggiornata e applicata.",
        "Updated.": "Aggiornata.",
        "Removed.": "Rimossa.",
        "Fields filled.": "Modulo compilato.",
        "Saved resolutions for {output}": "Risoluzioni salvate — {output}",
        "No saved resolutions for this monitor.": "Nessuna risoluzione salvata per questo monitor.",
    },
}


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def write_po(lang: str, entries: dict[str, str]) -> None:
    lines = [HEADER.format(lang=lang).strip(), ""]
    for msgid in MSGIDS:
        msgstr = entries.get(msgid, msgid)
        lines.append(f'msgid "{_escape(msgid)}"')
        lines.append(f'msgstr "{_escape(msgstr)}"')
        lines.append("")
    path = PO_DIR / f"{lang}.po"
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {path.name}")


def main() -> None:
    for lang in ("pt_BR", "fr", "es", "ru", "ko", "de", "zh_CN", "zh_TW", "ja", "ar", "hi", "it"):
        catalog = {msgid: msgid for msgid in MSGIDS}
        catalog.update(TRANSLATIONS.get(lang, {}))
        catalog.update(CORE_EXTRA_TRANSLATIONS.get(lang, {}))
        catalog.update(NEW_UI_TRANSLATIONS.get(lang, {}))
        write_po(lang, catalog)


if __name__ == "__main__":
    main()
